export const CITIES = [
  "Água Branca",
  "Anadia",
  "Arapiraca",
  "Atalaia",
  "Barra de Santo Antônio",
  "Barra de São Miguel",
  "Batalha",
  "Belém",
  "Belo Monte",
  "Boca da Mata",
  "Branquinha",
  "Cacimbinhas",
  "Cajueiro",
  "Campestre",
  "Campo Alegre",
  "Campo Grande",
  "Canapi",
  "Capela",
  "Carneiros",
  "Chã Preta",
  "Coité do Nóia",
  "Colônia Leopoldina",
  "Coqueiro Seco",
  "Coruripe",
  "Craíbas",
  "Delmiro Gouveia",
  "Dois Riachos",
  "Estrela de Alagoas",
  "Feira Grande",
  "Feliz Deserto",
  "Flexeiras",
  "Girau do Ponciano",
  "Ibateguara",
  "Igaci",
  "Igreja Nova",
  "Inhapi",
  "Jacaré dos Homens",
  "Jacuípe",
  "Japaratinga",
  "Jaramataia",
  "Jequiá da Praia",
  "Joaquim Gomes",
  "Jundiá",
  "Junqueiro",
  "Lagoa da Canoa",
  "Limoeiro de Anadia",
  "Maceió",
  "Major Isidoro",
  "Mar Vermelho",
  "Maragogi",
  "Maravilha",
  "Marechal Deodoro",
  "Maribondo",
  "Mata Grande",
  "Matriz de Camaragibe",
  "Messias",
  "Minador do Negrão",
  "Monteirópolis",
  "Murici",
  "Novo Lino",
  "Olho d Água das Flores",
  "Olho d Água do Casado",
  "Olho d Água Grande",
  "Olivença",
  "Ouro Branco",
  "Palestina",
  "Palmeira dos Índios",
  "Pão de Açúcar",
  "Pariconha",
  "Paripueira",
  "Passo de Camaragibe",
  "Paulo Jacinto",
  "Penedo",
  "Piaçabuçu",
  "Pilar",
  "Pindoba",
  "Piranhas",
  "Poço das Trincheiras",
  "Porto Calvo",
  "Porto de Pedras",
  "Porto Real do Colégio",
  "Quebrangulo",
  "Rio Largo",
  "Roteiro",
  "Santa Luzia do Norte",
  "Santana do Ipanema",
  "Santana do Mundaú",
  "São Brás",
  "São José da Laje",
  "São José da Tapera",
  "São Luís do Quitunde",
  "São Miguel dos Campos",
  "São Miguel dos Milagres",
  "São Sebastião",
  "Satuba",
  "Senador Rui Palmeira",
  "Tanque d'Arca",
  "Taquarana",
  "Teotônio Vilela",
  "Traipu",
  "União dos Palmares",
  "Viçosa",
];

export const STATUS_ITEMS = [
  "Fiel a Ficante",
  "Solteiro",
  "Casado",
  "Divorciado",
  "Namorando",
  "Separado",
  "União Estável",
  "Nunca namorei, mas observo...",
  "Último romântico",
];

export const SINGLE_STATUS_ITEMS = [
  "Emocionado",
  "Humilhado",
  "Encalhado",
  "Pra titia",
  "Desiludido",
  "Oi, vi que você apagou as fotos com o seu EX tá tudo bem?",
  "Só solteiro mesmo",
  "Golpe",
];

export const JOBS = [
  "Engenheiro de Software",
  "Médico",
  "Advogado",
  "Professor",
  "Enfermeiro",
  "Arquiteto",
  "Contador",
  "Designer Gráfico",
  "Analista de Dados",
  "Engenheiro Civil",
  "Dentista",
  "Psicólogo",
  "Farmacêutico",
  "Fisioterapeuta",
  "Jornalista",
  "Biólogo",
  "Geógrafo",
  "Historiador",
  "Engenheiro Elétrico",
  "Economista",
  "Engenheiro Mecânico",
  "Chef de Cozinha",
  "Piloto de Avião",
  "Administrador de Empresas",
  "Bibliotecário",
  "Tradutor",
  "Cientista da Computação",
  "Químico",
  "Veterinário",
  "Assistente Social",
  "Eletricista",
  "Mecânico de Automóveis",
  "Pedreiro",
  "Carpinteiro",
  "Soldador",
  "Operador de Máquinas",
  "Técnico em Informática",
  "Garçom",
  "Motorista",
  "Policial",
  "Bombeiro",
  "Fotógrafo",
  "Artista Plástico",
  "Escritor",
  "Ator",
  "Cantor",
  "Músico",
  "Cineasta",
  "Diretor de Teatro",
  "Produtor Musical",
  "Barbeiro",
  "Cabeleireiro",
  "Massagista",
  "Manicure",
  "Esteticista",
  "Engenheiro de Produção",
  "Engenheiro Ambiental",
  "Técnico em Segurança do Trabalho",
  "Técnico em Enfermagem",
  "Agente de Viagens",
  "Agente de Seguros",
  "Analista de Sistemas",
  "Analista Financeiro",
  "Assistente Administrativo",
  "Atendente de Farmácia",
  "Auxiliar de Laboratório",
  "Auxiliar de Limpeza",
  "Auxiliar de Produção",
  "Auxiliar de Serviços Gerais",
  "Balconista",
  "Biomédico",
  "Cantoneiro",
  "Carteiro",
  "Cozinheiro",
  "Diagramador",
  "Diretor de Cinema",
  "Editor de Vídeo",
  "Eletrônico",
  "Encanador",
  "Engenheiro de Controle e Automação",
  "Engenheiro de Minas",
  "Engenheiro de Petróleo",
  "Engenheiro de Projetos",
  "Engenheiro de Segurança do Trabalho",
  "Engenheiro Florestal",
  "Enólogo",
  "Especialista em Logística",
  "Especialista em Recursos Humanos",
  "Estatístico",
  "Fonoaudiólogo",
  "Gelólogo",
  "Gerente Comercial",
  "Gerente de Marketing",
  "Gerente de Projetos",
  "Gestor Ambiental",
  "Gestor Hospitalar",
  "Guia de Turismo",
  "Ilustrador",
  "Imunologista",
  "Inspetor de Qualidade",
  "Açougueiro",
  "Administrador de Redes",
  "Agente de Trânsito",
  "Agrônomo",
  "Alfaiate",
  "Almoxarife",
  "Antropólogo",
  "Apicultor",
  "Arqueólogo",
  "Arrematador",
  "Artesão",
  "Astrônomo",
  "Atendente de Call Center",
  "Auditor",
  "Auxiliar de Cozinha",
  "Bancário",
  "Bioquímico",
  "Borracheiro",
  "Cenógrafo",
  "Ceramista",
  "Chaveiro",
  "Cientista Político",
  "Climatologista",
  "Confeiteiro",
  "Conferente",
  "Conselheiro Tutelar",
  "Consultor de Negócios",
  "Controlador de Tráfego Aéreo",
  "Coreógrafo",
  "Costureiro",
  "Decorador",
  "Degustador",
  "Despachante Aduaneiro",
  "Despachante Imobiliário",
  "Dublador",
  "Econometrista",
  "Editor de Texto",
  "Educador Físico",
  "Engenheiro Aeronáutico",
  "Engenheiro de Alimentos",
  "Engenheiro de Materiais",
  "Engenheiro de Telecomunicações",
  "Engenheiro Mecatrônico",
  "Entomólogo",
  "Escultor",
  "Especialista em Comércio Exterior",
  "Especialista em TI",
  "Estilista",
  "Examinador de Trânsito",
  "Físico",
  "Fonoaudiólogo",
  "Garimpeiro",
  "Gastrônomo",
  "Genealogista",
  "Geofísico",
  "Geólogo",
  "Gerente de Recursos Humanos",
  "Gestor de Eventos",
  "Gestor de Turismo",
  "Ginecologista",
  "Hematologista",
  "Hidrólogo",
  "Homeopata",
  "Importador",
  "Instrutor de Autoescola",
  "Interprete de Libras",
  "Jardineiro",
  "Jornalista de Moda",
  "Lavador de Carros",
  "Leiloeiro",
  "Linguista",
  "Maestro",
  "Magistrado",
  "Marinheiro",
  "Marqueteiro",
  "Matemático",
  "Meteorologista",
  "Musicoterapeuta",
  "Nutricionista",
  "Oceanógrafo",
  "Oficial de Justiça",
  "Operador de Caixa",
  "Ortopedista",
  "Otorrinolaringologista",
  "Palhaço",
  "Paisagista",
  "Paleontólogo",
  "Pediatra",
  "Perito Criminal",
  "Pescador",
  "Petrógrafo",
  "Pianista",
  "Podólogo",
  "Policial Federal",
  "Policial Rodoviário",
  "Produtor de Eventos",
  "Psicopedagogo",
  "Quiropraxista",
  "Recepcionista",
  "Redator",
  "Revisor de Texto",
  "Roteirista",
  "Sanitarista",
  "Sapateiro",
  "Secretária Executiva",
  "Serralheiro",
  "Sociólogo",
  "Sommelier",
  "Técnico Agrícola",
  "Técnico de Laboratório",
  "Técnico em Agropecuária",
  "Técnico em Eletrotécnica",
  "Técnico em Mecânica",
  "Técnico em Prótese Dentária",
  "Técnico em Radiologia",
  "Telefonista",
  "Terapeuta Ocupacional",
  "Topógrafo",
  "Tosador de Animais",
  "Vendedor",
  "Vigilante",
  "Web Designer",
  "Zelador",
  "Zootecnista"
]

export const HOBBIES = [
  "Ler",
  "Escrever",
  "Desenhar",
  "Pintar",
  "Fotografia",
  "Caminhada",
  "Ciclismo",
  "Jardinagem",
  "Cozinhar",
  "Assar",
  "Pescar",
  "Acampar",
  "Escalada",
  "Yoga",
  "Meditação",
  "Natação",
  "Corrida",
  "Dança",
  "Tocar um instrumento musical",
  "Cantar",
  "Ouvir música",
  "Assistir filmes",
  "Assistir séries",
  "Jogos de tabuleiro",
  "Jogos de cartas",
  "Video games",
  "Modelismo",
  "Costura",
  "Tricô",
  "Crochê",
  "Colecionar",
  "Viajar",
  "Astronomia",
  "Observação de aves",
  "Carpintaria",
  "Marcenaria",
  "Puzzles",
  "Artesanato",
  "Escultura",
  "Cerâmica",
  "Aprender línguas",
  "Blogging",
  "Vlogging",
  "Podcasting",
  "Genealogia",
  "Voluntariado",
  "Tai Chi",
  "Pilates",
  "Pesca submarina",
  "Mergulho",
  "Fotografia subaquática",
  "Esgrima",
  "Boxe",
  "Kickboxing",
  "Arco e flecha",
  "Paintball",
  "Airsoft",
  "Criação de conteúdo",
  "Animação",
  "Design gráfico",
  "Editoração",
  "Produção de filmes",
  "Teatro",
  "Maquiagem artística",
  "Cosplay",
  "Fazenda urbana",
  "Aquarismo",
  "Terrários",
  "Cerveja artesanal",
  "Vinho artesanal",
  "Café artesanal",
  "Chá artesanal",
  "Lutheria",
  "Manutenção de bicicletas",
  "Restaurar móveis",
  "Caça",
  "Sobrevivencialismo",
  "Geocaching",
  "Caça ao tesouro",
  "Passeios históricos",
  "Exploração urbana",
  "Paddleboarding",
  "Kitesurf",
  "Surf",
  "Windsurf",
  "Canoagem",
  "Rafting",
  "Vela",
  "Modelagem 3D",
  "Impressão 3D",
  "Robótica",
  "Programação",
  "Hacking ético",
  "Criptografia",
  "Bolsa de valores",
  "Investimentos",
  "Marketing digital",
  "Desenvolvimento de aplicativos",
  "Inteligência artificial",
  "Realidade virtual",
  "Realidade aumentada",
  "Simulação de voo",
  "Aviação",
  "Aero-modelismo",
  "Automodelismo",
  "Ferromodelismo",
  "Estação meteorológica caseira",
  "Observação de tempestades",
  "Meteorologia",
  "Luta"
]
